name = "Odrpack"
uuid = "8771e72f-1726-44cc-8528-8e528679e212"
authors = ["HugoMVale <57530119+HugoMVale@users.noreply.github.com>"]
version = "0.1.0"

[deps]
odrpack_jll = "d4b606b2-00e0-534d-b821-fa459008cf27"

[compat]
odrpack_jll = "2.0.3"
 
[platforms]
aarch64-apple-darwin = false
aarch64-linux-gnu = true
aarch64-unknown-freebsd = true
armv6l-linux-gnueabihf = true
armv7l-linux-gnueabihf = true
i686-linux-gnu = true
i686-w64-mingw32 = true
powerpc64le-linux-gnu = true
riscv64-linux-gnu = true
x86_64-apple-darwin = false
x86_64-linux-gnu = true
x86_64-unknown-freebsd = true
x86_64-w64-mingw32 = false