name = "Odrpack"
uuid = "8771e72f-1726-44cc-8528-8e528679e212"
authors = ["HugoMVale <57530119+HugoMVale@users.noreply.github.com>"]
version = "0.1.0"

[deps]
odrpack_jll = "d4b606b2-00e0-534d-b821-fa459008cf27"

[compat]
odrpack_jll = "2.0.3"
julia = "1.6"
