name: Test

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.6' # LTS
          - '1.9' # Current stable
          - '1'   # Latest stable
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
      fail-fast: false # Don't cancel other matrix jobs if one fails

    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}

      - uses: julia-actions/cache@v2
        with:
          cache-key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.version }}

      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1
