name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'lts'
          - '1.10'
        os:
          - ubuntu-latest
          #- windows-latest
          #- macOS-latest
        exclude:
          - os: macOS-latest
            version: 'lts'
        # include:
        #   - os: macOS-13
        #     version: 'lts'

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies (OpenBLAS)
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
