name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: [ 'lts', '1', 'pre' ]
        julia-arch: [ 'x64' ]
        os: [ 'ubuntu-latest', 'windows-latest', 'macOS-13', 'macOS-latest' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}

      - name: Cache
        uses: julia-actions/cache@v2
        
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        uses: julia-actions/julia-runtest@v1

      - name: Process coverage
        if: ${{ matrix.julia-version == 'lts' && matrix.os == 'ubuntu-latest' }}
        uses: julia-actions/julia-processcoverage@v1

    #   - name: Show coverage
    #     if: ${{ matrix.julia-version == 'lts' && matrix.os == 'ubuntu-latest' }}
    #     run: cat lcov.info | head -n 40

    #   - name: Upload coverage to Codecov
    #     if: ${{ matrix.julia-version == 'lts' && matrix.os == 'ubuntu-latest' }}
    #     uses: codecov/codecov-action@v5
    #     with:
    #       token: ${{ secrets.CODECOV_TOKEN }}
    #       verbose: true
    #       files: lcov.info

      - name: Upload coverage to coveralls.io
        if: ${{ matrix.julia-version == 'lts' && matrix.os == 'ubuntu-latest' }}
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}